name: comp-methods-intro
# Minimal environment to run python_intro.ipynb at mybinder.org
# This environment does not work for turtle_graphics.ipynb
# The environment for local installation is given by 
# docs/environment.yml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - numpy=1.21.2
  - matplotlib=3.4.3
