name: comp-methods
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - scipy
  - sympy
  - pandas
  - ipykernel
  - ipympl
  - ipycanvas
  - jupyterlab
  - jupyterlab-git
  - git