name: comp-methods
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.1.18
  - numpy=1.21.2
  - matplotlib=3.4.3
  - ipympl=0.8.0
  - scipy=1.7.1
  - sympy=1.9
  - pandas=1.3.3
  - git=2.33.0
  - jupyterlab-git=0.33.0
  - rise=5.7.1
